from __future__ import annotations

from sqlalchemy.orm import Session

from ..models.psychographic_profile import (
    PsychographicQuestion,
    QuestionOption,
)


# Assessment questions designed to identify player archetypes
ASSESSMENT_QUESTIONS = [
    {
        "question_text": "When building a Magic deck, what excites you most?",
        "category": "deck_building",
        "order": 1,
        "options": [
            {
                "option_text": "Playing cards with huge numbers or dramatic effects that dominate the game",
                "order": 1,
                "timmy_weight": 0.5,
                "johnny_weight": 0.1,
                "spike_weight": 0.1,
                "vorthos_weight": 0.1,
                "melvin_weight": 0.1,
                "power_gamer_weight": 0.8,
                "social_gamer_weight": 0.1,
                "adrenaline_weight": 0.2,
            },
            {
                "option_text": "Creating unique synergies and interactions nobody else has thought of",
                "order": 2,
                "timmy_weight": 0.1,
                "johnny_weight": 0.5,
                "spike_weight": 0.1,
                "vorthos_weight": 0.1,
                "melvin_weight": 0.1,
                "combo_builder_weight": 0.8,
                "offbeat_builder_weight": 0.2,
                "architect_weight": 0.3,
            },
            {
                "option_text": "Finding the optimal cards and tuning every matchup for maximum win rate",
                "order": 3,
                "timmy_weight": 0.1,
                "johnny_weight": 0.1,
                "spike_weight": 0.5,
                "vorthos_weight": 0.1,
                "melvin_weight": 0.1,
                "competitive_weight": 0.8,
                "technical_weight": 0.7,
                "meta_analyst_weight": 0.6,
            },
        ],
    },
    {
        "question_text": "What do you value most in a card?",
        "category": "card_evaluation",
        "order": 2,
        "options": [
            {
                "option_text": "How impactful and exciting it feels to play",
                "order": 1,
                "timmy_weight": 0.5,
                "johnny_weight": 0.2,
                "spike_weight": 0.1,
                "vorthos_weight": 0.1,
                "melvin_weight": 0.1,
                "power_gamer_weight": 0.6,
                "social_gamer_weight": 0.5,
                "adrenaline_weight": 0.7,
            },
            {
                "option_text": "Whether it creates interesting design space or unique interactions",
                "order": 2,
                "timmy_weight": 0.1,
                "johnny_weight": 0.5,
                "spike_weight": 0.1,
                "vorthos_weight": 0.2,
                "melvin_weight": 0.3,
                "combo_builder_weight": 0.7,
                "architect_weight": 0.6,
                "lore_weight": 0.2,
                "mechanics_weight": 0.6,
            },
            {
                "option_text": "How it performs in the meta and its competitive viability",
                "order": 3,
                "timmy_weight": 0.1,
                "johnny_weight": 0.1,
                "spike_weight": 0.5,
                "vorthos_weight": 0.1,
                "melvin_weight": 0.1,
                "competitive_weight": 0.8,
                "technical_weight": 0.6,
                "meta_analyst_weight": 0.8,
            },
            {
                "option_text": "The story it tells and the flavor text",
                "order": 4,
                "timmy_weight": 0.2,
                "johnny_weight": 0.2,
                "spike_weight": 0.05,
                "vorthos_weight": 0.6,
                "melvin_weight": 0.1,
                "lore_weight": 0.9,
                "social_gamer_weight": 0.3,
            },
        ],
    },
    {
        "question_text": "In a game, you're most proud when you accomplish:",
        "category": "satisfaction",
        "order": 3,
        "options": [
            {
                "option_text": "An unexpected, spectacular turn where you win out of nowhere",
                "order": 1,
                "timmy_weight": 0.5,
                "johnny_weight": 0.2,
                "spike_weight": 0.1,
                "vorthos_weight": 0.1,
                "melvin_weight": 0.1,
                "power_gamer_weight": 0.7,
                "adrenaline_weight": 0.8,
                "social_gamer_weight": 0.4,
            },
            {
                "option_text": "Pulling off a complex combo or winning with your unique deck idea",
                "order": 2,
                "timmy_weight": 0.2,
                "johnny_weight": 0.5,
                "spike_weight": 0.1,
                "vorthos_weight": 0.1,
                "melvin_weight": 0.2,
                "combo_builder_weight": 0.8,
                "architect_weight": 0.7,
                "mechanics_weight": 0.5,
            },
            {
                "option_text": "Playing perfectly and outskilling your opponent",
                "order": 3,
                "timmy_weight": 0.1,
                "johnny_weight": 0.1,
                "spike_weight": 0.5,
                "vorthos_weight": 0.1,
                "melvin_weight": 0.1,
                "competitive_weight": 0.8,
                "technical_weight": 0.8,
            },
            {
                "option_text": "Having fun with friends and laughing about memorable moments",
                "order": 4,
                "timmy_weight": 0.4,
                "johnny_weight": 0.2,
                "spike_weight": 0.1,
                "vorthos_weight": 0.2,
                "melvin_weight": 0.05,
                "social_gamer_weight": 0.9,
                "power_gamer_weight": 0.3,
            },
        ],
    },
    {
        "question_text": "How do you typically approach learning about Magic rules?",
        "category": "learning_style",
        "order": 4,
        "options": [
            {
                "option_text": "You jump in and learn by playing; rules details come naturally",
                "order": 1,
                "timmy_weight": 0.5,
                "johnny_weight": 0.2,
                "spike_weight": 0.1,
                "vorthos_weight": 0.2,
                "melvin_weight": 0.1,
                "power_gamer_weight": 0.4,
                "social_gamer_weight": 0.6,
                "adrenaline_weight": 0.5,
            },
            {
                "option_text": "You experiment with interactions to understand how things work together",
                "order": 2,
                "timmy_weight": 0.2,
                "johnny_weight": 0.5,
                "spike_weight": 0.1,
                "vorthos_weight": 0.1,
                "melvin_weight": 0.4,
                "combo_builder_weight": 0.7,
                "mechanics_weight": 0.8,
                "architect_weight": 0.6,
            },
            {
                "option_text": "You study rules systematically to understand every detail and edge case",
                "order": 3,
                "timmy_weight": 0.05,
                "johnny_weight": 0.1,
                "spike_weight": 0.5,
                "vorthos_weight": 0.1,
                "melvin_weight": 0.5,
                "technical_weight": 0.8,
                "meta_analyst_weight": 0.6,
                "mechanics_weight": 0.7,
            },
            {
                "option_text": "You learn through reading flavor and lore, and connect mechanics to story",
                "order": 4,
                "timmy_weight": 0.2,
                "johnny_weight": 0.2,
                "spike_weight": 0.05,
                "vorthos_weight": 0.6,
                "melvin_weight": 0.2,
                "lore_weight": 0.9,
            },
        ],
    },
    {
        "question_text": "When you lose a game, what bothers you most?",
        "category": "losing_response",
        "order": 5,
        "options": [
            {
                "option_text": "Missing a chance for a spectacular play or awesome moment",
                "order": 1,
                "timmy_weight": 0.5,
                "johnny_weight": 0.2,
                "spike_weight": 0.1,
                "vorthos_weight": 0.1,
                "melvin_weight": 0.1,
                "power_gamer_weight": 0.6,
                "adrenaline_weight": 0.7,
            },
            {
                "option_text": "Not getting to show off what your deck can do",
                "order": 2,
                "timmy_weight": 0.2,
                "johnny_weight": 0.5,
                "spike_weight": 0.2,
                "vorthos_weight": 0.1,
                "melvin_weight": 0.1,
                "combo_builder_weight": 0.6,
                "offbeat_builder_weight": 0.7,
                "architect_weight": 0.5,
            },
            {
                "option_text": "Making a mistake or not playing optimally",
                "order": 3,
                "timmy_weight": 0.1,
                "johnny_weight": 0.1,
                "spike_weight": 0.6,
                "vorthos_weight": 0.05,
                "melvin_weight": 0.15,
                "competitive_weight": 0.8,
                "technical_weight": 0.8,
                "meta_analyst_weight": 0.5,
            },
            {
                "option_text": "Missing out on a fun game experience with friends",
                "order": 4,
                "timmy_weight": 0.4,
                "johnny_weight": 0.2,
                "spike_weight": 0.1,
                "vorthos_weight": 0.2,
                "melvin_weight": 0.05,
                "social_gamer_weight": 0.9,
            },
        ],
    },
    {
        "question_text": "What's your favorite way to interact with Magic content outside of playing?",
        "category": "content_engagement",
        "order": 6,
        "options": [
            {
                "option_text": "Watching impressive plays and deck highlight videos",
                "order": 1,
                "timmy_weight": 0.5,
                "johnny_weight": 0.2,
                "spike_weight": 0.2,
                "vorthos_weight": 0.1,
                "melvin_weight": 0.1,
                "power_gamer_weight": 0.7,
                "adrenaline_weight": 0.6,
            },
            {
                "option_text": "Brewing creative decks and exploring what's possible",
                "order": 2,
                "timmy_weight": 0.1,
                "johnny_weight": 0.6,
                "spike_weight": 0.1,
                "vorthos_weight": 0.1,
                "melvin_weight": 0.2,
                "combo_builder_weight": 0.8,
                "offbeat_builder_weight": 0.7,
            },
            {
                "option_text": "Analyzing competitive meta and studying top decks",
                "order": 3,
                "timmy_weight": 0.1,
                "johnny_weight": 0.1,
                "spike_weight": 0.6,
                "vorthos_weight": 0.05,
                "melvin_weight": 0.2,
                "competitive_weight": 0.9,
                "meta_analyst_weight": 0.9,
                "technical_weight": 0.7,
            },
            {
                "option_text": "Reading lore and enjoying the stories in the cards",
                "order": 4,
                "timmy_weight": 0.1,
                "johnny_weight": 0.2,
                "spike_weight": 0.05,
                "vorthos_weight": 0.7,
                "melvin_weight": 0.1,
                "lore_weight": 0.95,
            },
            {
                "option_text": "Understanding rules interactions and mechanical elegance",
                "order": 5,
                "timmy_weight": 0.1,
                "johnny_weight": 0.2,
                "spike_weight": 0.2,
                "vorthos_weight": 0.1,
                "melvin_weight": 0.6,
                "mechanics_weight": 0.9,
                "architect_weight": 0.6,
            },
        ],
    },
]


def bootstrap_assessment_questions(db: Session) -> None:
    """
    Load default assessment questions into the database.
    Idempotent - safe to call multiple times.
    """
    # Check if questions already exist
    existing_count = db.query(PsychographicQuestion).count()
    if existing_count > 0:
        return  # Already loaded
    
    for question_data in ASSESSMENT_QUESTIONS:
        question = PsychographicQuestion(
            question_text=question_data["question_text"],
            category=question_data["category"],
            order=question_data["order"],
        )
        db.add(question)
        db.flush()  # Flush to get the question ID
        
        for option_data in question_data["options"]:
            option = QuestionOption(
                question_id=question.id,
                option_text=option_data["option_text"],
                order=option_data["order"],
                timmy_weight=option_data.get("timmy_weight", 0.0),
                johnny_weight=option_data.get("johnny_weight", 0.0),
                spike_weight=option_data.get("spike_weight", 0.0),
                vorthos_weight=option_data.get("vorthos_weight", 0.0),
                melvin_weight=option_data.get("melvin_weight", 0.0),
                power_gamer_weight=option_data.get("power_gamer_weight", 0.0),
                social_gamer_weight=option_data.get("social_gamer_weight", 0.0),
                adrenaline_weight=option_data.get("adrenaline_weight", 0.0),
                combo_builder_weight=option_data.get("combo_builder_weight", 0.0),
                offbeat_builder_weight=option_data.get("offbeat_builder_weight", 0.0),
                architect_weight=option_data.get("architect_weight", 0.0),
                competitive_weight=option_data.get("competitive_weight", 0.0),
                technical_weight=option_data.get("technical_weight", 0.0),
                meta_analyst_weight=option_data.get("meta_analyst_weight", 0.0),
                lore_weight=option_data.get("lore_weight", 0.0),
                mechanics_weight=option_data.get("mechanics_weight", 0.0),
            )
            db.add(option)
    
    db.commit()
